server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: password
    key-alias: localhost

app:
  config-server: localhost

spring.cloud.gateway.routes:
- id: product-composite
  uri: http://product-composite
  predicates:
  - Path=/product-composite/**

- id: oauth-server
  uri: http://${app.auth-server}
  predicates:
    - Path=/oauth/**

- id: config-server
  uri: http://${app.config-server}:8888
  predicates:
    - Path=/config/**
  filters:
    - RewritePath=/config/(?<segment>.*), /$\{segment}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://${app.auth-server}/.well-known/jwks.json

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE

---
spring:
  config:
    activate:
      on-profile: docker

app:
  config-server: config-server

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: WARN
    org.springframework.cloud.gateway: WARN
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: WARN